/* auto-generated by gensrv_java from /home/dhewlett/ros/ua-ros-pkg/ua_experimental/time_series/srv/TestSignature.srv.  Do not edit! */
package ros.pkg.time_series.srv;

import java.nio.ByteBuffer;

public class TestSignature extends ros.communication.Service<TestSignature.Request, TestSignature.Response> 
{

public static String __s_getDataType() { return "time_series/TestSignature"; }
public static String __s_getMD5Sum() { return "51b38d7107b10f0304efa756e9691f90"; }

public String getDataType() { return TestSignature.__s_getDataType(); }
public String getMD5Sum() { return TestSignature.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{

  public java.lang.String verb;
  public ros.pkg.time_series.msg.Episode episode;
  public int min;

  public Request() {
 super();
    verb = new java.lang.String();
    episode = new ros.pkg.time_series.msg.Episode();

  }
  public static java.lang.String __s_getDataType() { return "time_series/TestSignatureRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "string verb\n" + 
    "time_series/Episode episode\n" + 
    "int32 min\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("51b38d7107b10f0304efa756e9691f90"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("time_series/TestSignature"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
      episode = (ros.pkg.time_series.msg.Episode)episode.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("verb", "java.lang.String");
     m.put("episode", "ros.pkg.time_series.msg.Episode");
     m.put("min", "int");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      s.add("ros.pkg.time_series.msg.Episode");
     return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    verb = __m2.verb;
    episode = __m2.episode;
    min = __m2.min;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += 4 + verb.length(); // verb
    __l += episode.serializationLength(); // episode
    __l += 4; // min
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, verb);
     episode.serialize(bb, seq);
    bb.putInt(min);
  }
  public void deserialize(ByteBuffer bb)  {
    verb = Serialization.readString(bb);
     episode.deserialize(bb);
    min = bb.getInt();
  }
}

public static class Response extends ros.communication.Message
{

  public double score;

  public Response() {
 super();

  }
  public static java.lang.String __s_getDataType() { return "time_series/TestSignatureResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "float64 score\n" + 
    "================================================================================\n" + 
    "MSG: time_series/Episode\n" + 
    "time_series/Interval[] intervals\n" + 
    "================================================================================\n" + 
    "MSG: time_series/Interval\n" + 
    "string proposition\n" + 
    "int32 start\n" + 
    "int32 end\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("51b38d7107b10f0304efa756e9691f90"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("time_series/TestSignature"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("score", "double");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    score = __m2.score;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += 8; // score
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    bb.putDouble(score);
  }
  public void deserialize(ByteBuffer bb)  {
    score = bb.getDouble();
  }
}

public TestSignature.Request createRequest() { return new TestSignature.Request(); }public TestSignature.Response createResponse() { return new TestSignature.Response(); }}

